#include <stdint.h>
#include <stdlib.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/i2s_std.h"
#include "driver/gpio.h"

static const char *TAG = "I2S_INMP441";

#define EXAMPLE_STD_BCLK_IO1_RX GPIO_NUM_8  // I2S bit clock io number
#define EXAMPLE_STD_WS_IO1_RX GPIO_NUM_3    // I2S word select io number
#define EXAMPLE_STD_DOUT_IO1_RX GPIO_NUM_NC // I2S data out io number
#define EXAMPLE_STD_DIN_IO1_RX GPIO_NUM_18  // I2S data in io number
#define CONFIG_EXAMPLE_SAMPLE_RATE 44100
// static i2s_chan_handle_t tx_chan; // I2S tx channel handler
static i2s_chan_handle_t rx_chan; // I2S rx channel handler


void i2s_example_init_std_duplex(void)
{
    /* Setp 1: Determine the I2S channel configuration and allocate both channels
     * The default configuration can be generated by the helper macro,
     * it only requires the I2S controller id and I2S role */
    i2s_chan_config_t chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(0, I2S_ROLE_MASTER);
    ESP_ERROR_CHECK(i2s_new_channel(&chan_cfg, NULL, &rx_chan));

    /* Step 2: Setting the configurations of standard mode, and initialize rx & tx channels
     * The slot configuration and clock configuration can be generated by the macros
     * These two helper macros is defined in 'i2s_std.h' which can only be used in STD mode.
     * They can help to specify the slot and clock configurations for initialization or re-configuring */
    i2s_std_config_t std_cfg = {
        .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(CONFIG_EXAMPLE_SAMPLE_RATE),
        .slot_cfg = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_32BIT, I2S_SLOT_MODE_MONO),
        .gpio_cfg =
            {
                .mclk = I2S_GPIO_UNUSED, // some codecs may require mclk signal, this example doesn't need it
                .bclk = EXAMPLE_STD_BCLK_IO1_RX,
                .ws = EXAMPLE_STD_WS_IO1_RX,
                .dout = I2S_GPIO_UNUSED,
                .din = EXAMPLE_STD_DIN_IO1_RX, // In duplex mode, bind output and input to a same gpio can loopback
                // internally
                .invert_flags =
                    {
                        .mclk_inv = false,
                        .bclk_inv = false,
                        .ws_inv = false,
                    },
            },
    };
    /* Initialize the channels */
    // ESP_ERROR_CHECK(i2s_channel_init_std_mode(tx_chan, &std_cfg));
    /* Default is only receiving left slot in mono mode,
     * update to right here to show how to change the default configuration */
    std_cfg.slot_cfg.slot_mask = I2S_STD_SLOT_LEFT;
    ESP_ERROR_CHECK(i2s_channel_init_std_mode(rx_chan, &std_cfg));
}